services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/root/todoServer/static
      - media_volume:/root/todoServer/media
    environment:
      - DJANGO_SETTINGS_MODULE=todoServer.settings
      - MYSQL_DATABASE=todo_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
      - SECRET_KEY=your_secret_key_here
      - DEBUG=False
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    networks:
      - app_network

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx/conf.d:/root/todoServer/nginx/conf.d
      - ./nginx/ssl:/root/todoServer/nginx/ssl
      - static_volume:/root/todoServer/static
      - media_volume:/root/todoServer/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  static_volume:
  media_volume: 