# Generated by Django 5.0 on 2024-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser_nickname_user_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserfeedback',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
    ]
