# Generated by Django 5.0 on 2024-12-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicaluserfeedback_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserfeedback',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
