# Generated by Django 5.0 on 2024-12-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
