# Generated by Django 5.0 on 2025-01-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tag_unique_together_remove_tag_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
