# Generated by Django 5.0 on 2025-01-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_historicaltask_start_time_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='instance_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='实例序号'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='重要'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='instance_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='实例序号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='重要'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划日期'),
        ),
        migrations.CreateModel(
            name='RepeatTaskDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(verbose_name='任务日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('repeat_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tasks.repeattask')),
            ],
            options={
                'verbose_name': '重复任务日期',
                'verbose_name_plural': '重复任务日期',
                'indexes': [models.Index(fields=['task_date'], name='tasks_repea_task_da_f3e50c_idx'), models.Index(fields=['repeat_task', 'task_date'], name='tasks_repea_repeat__fc86ce_idx')],
                'unique_together': {('repeat_task', 'task_date')},
            },
        ),
    ]
