# Generated by Django 5.0 on 2025-01-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_historicaltask_instance_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepeatTaskDate',
        ),
    ]
